name: 报告 Bug
title: "[Bug] "
description: 报告 误触/问题 规则
body:
  - type: markdown
    attributes:
      value: |
        ## 在提交问题之前，请确保您完成以下操作,否则你的issue可能会根据情况直接被关闭！
        如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

        1. 请 **确保** 提供 误触/出现问题 **的是** 界面的快照不是截图（截图没有任何作用），并知道是哪一条规则 误触/出现问题
        2. 请 **确保** 使用的是 [最新版订阅](https://github.com/mrlctate/gkd-mrlc/releases/latest) 和 [最新版GKD](https://github.com/gkd-kit/gkd/releases/latest)
        3. 请 **确保** 检查这个问题是属于 [本项目维护的规则](https://github.com/mrlctate/gkd-mrlc) 导致的
        4. 请 **确保** 提供下列BUG描述及其复现步骤, 否则您的问题将会被直接关闭
        5. 上传文件时请等待文件名前面的 Uploading 消失后再提交，否则文件将会上传失败

        #### 检查问题是否属于以下几种之一，如果属于请说明是哪一种（误触问题可忽略这条）
        1. 规则不生效，但是截取快照时生效/回到桌面（不杀后台）再进入软件后生效
        2. 规则触发了（有点击提示），但实际并不能生效（没有达到预期行为）

  - type: textarea
    id: bug-1
    attributes:
      label: |
        请提供 误触界面/出现问题的 记录、快照，也补充说明
      description: |
        快照是一个 zip 文件，快照链接是类似 "https://i.gkd.li/i/XXXXXXXX" 的文本，按照如下方式可获得快照信息

        按照下面的截图示例来获取界面快照，上传文件或者生成链接并粘贴到下面的输入框\
        ![img](https://user-images.githubusercontent.com/45487685/270372181-9e05a475-6664-4e1b-adc7-1e3973fff01f.png)

        此外需提供 快照链接
    validations:
      required: true
  - type: textarea
    id: bug-2
    attributes:
      label: |
        请说明是哪一条规则 误触/出现问题(文字/截图/视频)
    validations:
      required: true
